services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lgpd_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
